### ISSUE TITLE
tcp_res_flags is reserved and set, but so far as I can tell it is unused

### ISSUE THREAD

**Issue by dtaht** [chromi/sce#1]
it eats a word in the cb, but I don't see where you are using it. 

d@ceres:~/git/linux/fq_fixes$ rg tcp_res_flags
include/net/tcp.h
823:	__u8		tcp_res_flags;	/* TCP reserved flags. (tcp[12]) */

net/ipv4/tcp_ipv4.c
1774:	TCP_SKB_CB(skb)->tcp_res_flags = tcp_res_flag_byte(th);

**Comment by dtaht** [comment]
Nag.

**Comment by dtaht** [comment]
Another place to stick it if actually needed would be here, though I'm coping with the differences between bbrv2 and linux head at the moment.

 enum tcp_tw_status {
        TCP_TW_SUCCESS = 0,
@@ -823,7 +825,8 @@ struct tcp_skb_cb {
        __u8            txstamp_ack:1,  /* Record TX timestamp for ack? */
                        eor:1,          /* Is skb MSG_EOR marked? */
                        has_rxtstamp:1, /* SKB has a RX timestamp       */
-                       unused:5;
+                       tcp_res_flags:4, /* /* TCP reserved flags. (tcp[12]) */
+                       unused:1;
        __u32           ack_seq;        /* Sequence number ACK'd        */

**Comment by heistp** [comment]
Closing now, apparently that was added for consistency.
